/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        TreeMap map = new TreeMap();

        map.insert("keyOne", "valueOne");
        map.insert("keyTwo", "valueTwo");
        map.insert("keyThree", "valueThree");

        System.out.println(map.get("keyOne"));
        System.out.println(map.get("keyThree"));

        System.out.println(map.get("keyDNE"));

        System.out.println(map.delete("keyOne"));
    }
}
